name: Python autotests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run auto-tests
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run tests
        run: pytest

