name: Python autotests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run auto-tests
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run regrssion tests
        if: "github.event.inputs.deployment_target == 'regression'" 
        run: pytest -m regression
        continue-on-error: true
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'" 
        run: pytest -m smoke
        continue-on-error: true
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'" 
        run: pytest 
        continue-on-error: true
